import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar.jsx";
import TransitionProvider from "@/components/TransitionProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Shivam Dev Portfolio App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png", // or use "/favicon.png"
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TransitionProvider>{children}</TransitionProvider>
      </body>
    </html>
  );
}
